[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,@loader_path",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../lib",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../../lib",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../../../lib",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../../../../lib",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../../../../../lib",
]
